### ISSUE TITLE
Cannot read property 'converse' of undefined

### ISSUE THREAD

**Issue by Webunity** [greghesp/assistant-relay#126]
Tried it with and without converse param in POSTMAN, but i can't get it to work.
```
{ "converse": "true", "command": "test", "user": "frank", "broadcast": "true" }
```

The example in the readme doesn't give any hints about the requiredness of the converse parameter.
```
curl -d '{"command":"hello world", "user":"greg", "broadcast":"true"}' -H "Content-Type: application/json" -X POST http://<ip_address>:<port>/assistant
```

And executing it not in Postman but on my PI also gives:
```
pi:~$ curl -d '{"command":"hello world", "user":"greg", "broadcast":"true"}' -H "Content-Type: application/json" -X POST http://192.168.1.40:3000/assistant
```

Gives:
```
Cannot read property 'converse' of undefined
```

LOGS:
```
0|www  | TypeError: Cannot read property 'converse' of undefined
0|www  |     at new Conversation (/assistant_relay/node_modules/google-assistant/components/conversation.js:129:34)
0|www  |     at /assistant_relay/helpers/assistant.js:19:38
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Webunity** [comment]
Update: after issuing a command from the sandbox, which worked, i copied the JSON and it started working:
```
{
    "name": "frank",
    "converse": "false",
    "broadcast": true,
    "command": "this is a test"
}
```
No clue why

**Comment by Webunity** [comment]
Ah wait.. in the sample on the readme there is a mention of "USER" and here i see "NAME".

**Comment by greghesp** [comment]
I think thats a bug in the sandbox code generation.  It should be "user" and not "name".

I also think there is a typo in the Readme and in the Sandbox.  Can you try passing the converse param as a boolean, not a string?

`{ "converse":"true, "command": "test", "user": "frank", "broadcast": true }`

**Comment by ryancasler** [comment]
Something is wrong with the latest release.  Custom commands are no longer working but instead are issuing broadcasts no matter what is done. 

Previously I had used the example command "Tell me a joke."  That is no longer working in 3.0.4.

**Comment by greghesp** [comment]
@ryancasler You sure there wasn't something else? I've had a look in the code and tested myself and cannot find why it'd be doing that

![image](https://user-images.githubusercontent.com/768908/68606283-04cf5400-04a6-11ea-9771-950ef9a1b3dd.png)

**Comment by greghesp** [comment]
Thats..... odd.  It's null by default, so whatever it gets change to first should be that value.

Is that just a Sandbox submission
@Webunity Can you go into your config.json file and go to the users object.  You should see your user name, and inside the "tokens" object, you should see an expiry_date.  What is that date?

**Comment by ryancasler** [comment]
Okay, I don't know what is going on.  When I go in and use this:

{
    "user": "ryan",
    "command": "What time is it.",
}

It broadcasts "What time is it"  But then if I go in and try:
{
    "user": "ryan",
    "command": "What time is it.",
    "converse": false,
    "broadcast": false
}

It tells GAR what the time is and I can see that displayed and the sound file is there.

**Comment by ryancasler** [comment]
I think it's using what ever was set last.  Because now when I go in and try:
{
"user": "ryan",
"command": "What time is it.",
}

it does the same thing as 
{
"user": "ryan",
"command": "What time is it.",
"converse": false,
"broadcast": false
}

because that was the last way the flags were set.  So, basically, those flags always need to be set to make sure it uses the right ones.

**Comment by ryancasler** [comment]
Also, what is the "converse" flag actually doing?  it's just rebroadcasting the text response from Google Assistant, right?  Because using this:

{
    "user": "ryan",
    "command": "Tell me a joke.",
    "converse": true,
    "broadcast": false
}

Got a broadcast of 
What happens when a frog's car breaks?
It gets toad 🐸

But it actually said the words "Toad face" and it started with "Broadcast from Ryan".  Maybe we need to eliminate emoji from the message.

**Comment by greghesp** [comment]
@ryancasler  Can you open a new bug report for that and ill take a look

**Comment by ryancasler** [comment]
Sure.

**Comment by Webunity** [comment]
Is there some way to turn off the 'broadcast from' ? and just have it mention 'the dryer is ready?'

**Comment by Webunity** [comment]
> Thats..... odd. It's null by default, so whatever it gets change to first should be that value.
> 
> Is that just a Sandbox submission
> @Webunity Can you go into your config.json file and go to the users object. You should see your user name, and inside the "tokens" object, you should see an expiry_date. What is that date?

it was a fresh install + login and it works with `name` on my install (haven't updated yet)

**Comment by greghesp** [comment]
Hmm, I can't figure out whats causing this.  Seems to randomly happen.

The correct parameter is "user".  It's just ignoring the "name" param because it doesn't know what it is. Since you're the only user and you're not passing it as a param, it takes the first user you setup

**Comment by kylecauston** [comment]
> Is there some way to turn off the 'broadcast from' ? and just have it mention 'the dryer is ready?'

This would be very nice. Makes it sound like GA is announcing something, rather than being announced through.

**Comment by Webunity** [comment]
Does it happen on your end? If not, what is the countrycode of your linked google account?

**Comment by greghesp** [comment]
> Does it happen on your end? If not, what is the countrycode of your linked google account?

It happens randomly, but I haven't figured out what's causing it or how to fix it yet.
I thought maybe it happens when the auth token expires but I don't think that's the case

**Comment by ryancasler** [comment]
> Is there some way to turn off the 'broadcast from' ? and just have it mention 'the dryer is ready?'

Unfortunately you can't because it's part of the function of Google Assistant. Broadcasting voice messages, like you would from your phone or another speaker, that are in your voice and do not contain that message at the beginning, are not supported by the Google Assistant SDK that this program is based on.  This is a list of the supported feature of the SDK.

![image](https://user-images.githubusercontent.com/30270489/68905252-8aedd380-070e-11ea-97f9-98e6766d03c2.png)

**Comment by Webunity** [comment]
Unfortunately broadcasting voice messages is not supported, else you could pre-record a message and 'simulate' to Google you said it. I think this ticket can be closed.

**Comment by greghesp** [comment]
@Webunity  voice messages has nothing to do with this bug?

**Comment by Webunity** [comment]
yes and no; a possible work around could be that you don't send text, but voice; you might be able to 'fool' google by sending a pre-recorded message like "announce ..." after which the GA would think it was spoken by a user. But, this is not supported right now so lets don't take that indeed into consideration here.

**Comment by greghesp** [comment]
Sorry, i'm confused as to what this as to do with the original bug reported though?

**Comment by ryancasler** [comment]
It doesn't.  This was in regards to:

> Is there some way to turn off the 'broadcast from' ? and just have it mention 'the dryer is ready?'

**Comment by jaytaylor** [comment]
```Auth error:TypeError: Cannot read property 'access_token' of undefined```

```Cannot read property 'converse' of undefined```

Following a [HomeAssistant / HASSIO Assistant-Relay setup tutorial](https://www.youtube.com/watch?v=CUc6NEEbbeo), I encountered the above errors in the container logs when testing in the AR Sandbox.  Resolved by removing and reinstalling the add-on in HASSIO and re-creating / re-authenticating my assistant-relay user.

To me this suggests the culprit is likely that the access_token initialization failed the first time around.

After that, all errors have cleared up and Assistant-Relay is working magnificently!

Related issues:

https://github.com/greghesp/assistant-relay/issues/150
https://github.com/greghesp/assistant-relay/issues/126
https://github.com/greghesp/assistant-relay/issues/242

Hope this can help anyone else who encounters this class of issue in the future.

<3
