### ISSUE TITLE
Get device state change from Google Assistant/Google Home

### ISSUE THREAD

**Issue by jacekpaszkowski** [greghesp/assistant-relay#152]
**Is your feature request related to a problem? Please describe.**
I have some devices which are integrated only via GH. So i would like to get current state back to my HA when state is changed via GH/GA

Is it possible? :)

**Comment by greghesp** [comment]
I'm not entirely sure this is possible without seeing up an actions on Google project.

Even with that, I'm not sure if it'll report back automatically.
What about sending a command just asking for the state of device X?

**Comment by jacekpaszkowski** [comment]
How can i send request form HA to GH to get state ? I think it would be ok.

**Comment by greghesp** [comment]
I've not worked with HA or actually tested this with GA.
It's just a guess but can you ask Google Assistant if a device is turned on?  If so, that's your command.  If not, I dont know another way of doing it and its not something AR can support.

**Comment by ryancasler** [comment]
@jacekpaszkowski , are you asking if that status can be returned back to HA or broadcast on your speakers?  If the later, then yes, that would be the command and you would set converse to True.  If the former, parsing the scope of any response from GA isn't within the scope of AR.  The issue is that there is not a text response sent to AR when you ask a question like that.  If you go to the Sandbox and try it out, you will see this is the response:

![image](https://user-images.githubusercontent.com/30270489/73373912-5b6b5380-4287-11ea-8943-e7e633c100bd.png)

The audio file lists all of the lights that it responds about and they are correct, but the answer is not sent in any text that could be parsed and sent back to HA.
