### ISSUE TITLE
Authentication for Relay

### ISSUE THREAD

**Issue by gpetru1** [greghesp/assistant-relay#156]
Since I have the Relay server port forwarded to the internet for IFTT automations, it would be nice to have authentication for the web interface. I understand potentially calls could still be made to the server but at least the configuration and sandbox are not wide open. Thanks again for all of your hard work!

**Comment by ryancasler** [comment]
Are you integrating with some other home automation platform?  I resolve this by not exposing GAR to the internet but using the device created in my Hubitat to issue other announcements.  That system has security built in so it provides a buffer between GAR and the internet.  I know the same thing is possible with Samsung SmartThings and Home Assistant as well.  Just a possible workaround.

**Comment by greghesp** [comment]
I've been having a look at this, and it's a bit of a pain at the moment.  
Rather than port forwarding, have you looked at [ngrok](https://ngrok.com/)?

It's very simple to use, and I think it'd solve your problem quite quickly.

1. Sign up for Ngrok

2. Download the ngrok program to your Assistant Relay folder

3.  Connect your ngrok account using the command [here](https://dashboard.ngrok.com/get-started)

4. Start ngrok using the command in section 4.  For the port, use the port that Assistant Relay is running on

Ngrok will give you a URL, something like "https://13858332kg.ngrok.com:7989".  You can then just call this URL rather than your IP address and it'll securely route the request to Assistant Relay.

A word of warning though.  If Ngrok is restarted, you'll get a new URL to use.  You need to register for a basic account ($5/mo) to have a static ngrok URL

**Comment by Apipa169** [comment]
Using a reverse proxy such as Nginx will help. You can add whitelisting or basic authentication to protect it. However I'm not sure if basic auth is supported by IFTTT.

**Comment by greghesp** [comment]
I believe you can do `https://username:password@example.io` in your IFTTT webhook for basic auth

**Comment by greghesp** [comment]
@gpetru1 Please see [version 4 rework](https://github.com/greghesp/assistant-relay/issues/191) post. I'll leave this open until implemented

**Comment by greghesp** [comment]
@gpetru1  Added to v4.  If you want to **test** then clone the v4 branch, do `npm i` followed by `npm run dev`
