### ISSUE TITLE
Can't set timers

### ISSUE THREAD

**Issue by r-freeman** [greghesp/assistant-relay#172]
Thanks for the software. I'm a using a single Google Home Mini and I am unable to set timers (see screenshot below). I can control Phillips Hue with no issues. I'm not sure if this is intended or am I missing something?

![192 168 0 221_30000_sandbox (1)](https://user-images.githubusercontent.com/30879081/79009438-52d0ac80-7b57-11ea-9140-4f2b45b6a556.png)

**Comment by ryancasler** [comment]
That's not how Assistant Relay works.  First of all, you don't have your user name in the user field. 
 Second, to issue a command you have to not enable the broadcast setting.  Third, for custom commands you do not have to use "Hey Google" first.  Just issue the command (i.e. turn off the bedroom lights".   

However, you cannot use GAR to set timers or alarms on other devices.  And issuing that command to GAR won't do you any good because it doesn't have a speaker or it's own.  And setting a timer or alarm from the Google Assistant SDK is not supported.

**Comment by r-freeman** [comment]
Thanks for your help, I'll close this issue.
