### ISSUE TITLE
Support config.json filepath override via ENV var.

### ISSUE THREAD

**Issue by bgulla** [greghesp/assistant-relay#175]
**Is your feature request related to a problem? Please describe.**
As a kubernetes user, I would like to deploy assistant-relay as a docker. Unfortunately I would like to mount the `config.json` in a persistent-volume that is mounted outside of the expected `bin` directory.

**Describe the solution you'd like**
Please add the ability to set an environment variable to override the expected location of `config.json`.
example: `ASSISTANT_RELAY_CONFIG="/data/config.json"`

**Describe alternatives you've considered**
I wanted to load the config.json in as a kubernetes secret, but unfortunately assistant-relay requires the file to be writable, so I must use a k8s volume.

**Comment by greghesp** [comment]
I'm developing v4 at the moment, so will take a look as I think this may helper the Docker implementation too.

NB: AR won't work on a remote server due to SDK limitations

**Comment by greghesp** [comment]
I don't think this something I'm going to be looking into further unfortunately.  The json files are read/write based on the `lowdb` database library.  I may possibly look at adding in Firebase support so users can utilise remote data, but this isn't currently in my plans

**Comment by mnestor** [comment]
Well then here's how you can work around the issue provided the container has bash or ash installed. Was using ash but that broke in a recent change.

Just setup the entrypoint to symlink the config file

`entrypoint: 
      - /bin/bash
      - -c
      - |
        trap "break;exit" SIGHUP SIGINT SIGTERM
        ln -s /config/config.json /assistant_relay/bin/config.json
        /run.sh`

**Comment by greghesp** [comment]
Actually, I will re-open. Misread this, just passing the path should be fine

**Comment by greghesp** [comment]
Added in [Version 4 rework](https://github.com/greghesp/assistant-relay/issues/191)

**Comment by bradyemerson** [comment]
For those that would like to run this on docker before Version 4, I have a version available on docker hub: https://hub.docker.com/repository/docker/bradyemerson/assistant-relay

In my docker build, I rewrite all of the config references to /config/config.json.  At a minimum, it would be helpful if the config files was managed in a directory by itself rather than in /bin with all of the other files.  This would allow us to mount/inject into that directory without interfering with the operational files.
