### ISSUE TITLE
Nest Hub Max Won't Accept /cast/stop

### ISSUE THREAD

**Issue by DevTodd** [greghesp/assistant-relay#185]
**Describe the bug**
Cast stop works for all nest hubs and other speakers however I can't get it to work on the Hub Max.  Additionally, hub max devices do not show up in the cast sandbox either.  Enabling the cast is possible through a standard command.

**To Reproduce**
Send HTTP Post JSON encoded:
`{
    "device": "Hub Name"
    "force": true 
}`
 to http://ipaddress:port/cast/stop

**Expected behavior**
The hub max should stop casting

**Desktop (please complete the following information):**
-  Platform Raspberry Pi v4, using webCoRE for command automation.

**Comment by ryancasler** [comment]
Have you tried sending it along without the force true?  If the device allows casting to start there is nothing different about the cast implementation on the max that would not allow it to stop just like other Google Home devices.

**Comment by DevTodd** [comment]
Yes I have tried with force.  The same stream initiated and stopped correctly on 3 other devices all non-max, og hubs

**Comment by ryancasler** [comment]
Do you have the hub set to allow others to control your device in the Google Home App?

![image](https://user-images.githubusercontent.com/30270489/85796006-316b6f80-b707-11ea-91d9-2803f2c7fc9c.png)

**Comment by DevTodd** [comment]
Yes that was enabled.  I had to wait to check from home, at work it wouldn't let me.  Here's the difference between them.  The hub max is connected primarily in the nest app, all other regular hubs are connected directly to Google, non-nest.  That's the only thing I can imagine causing the issue.  Thoughts?

**Comment by ryancasler** [comment]
I'm sorry, I'm not quite understanding.  I thought you used the Google Home app to set up all Google Home devices.  So, wouldn't that be the "primary" connection?  Are you saying you can't see the Max in the Google Home app?  If not, that would certainly explain why it's not visible to AR.

**Comment by DevTodd** [comment]
No I'm not saying that.  Google calls the hub max the "nest hub max".  It is the only hub that's in the nest app as well as the Google home app.  That's because the camera can be used in the nest app and part of the nest subscription.  I haven't looked at the API at all, or dove into the difference between the devices.  I'm only offering a suggestion as to why there might be a difference.  To answer the question directly, yes the hub max is in the Google home app.

**Comment by ryancasler** [comment]
And the only problem is that you can't stop media that is laying on the
hub?  Do you have an android phone?  Do you see a notification on it while
media is playing on the hub to allow you to control said media?  Are you
trying to stop media that was ordered to be played by AR?

The only way to figure this out would be to try and run the commands from
CATT directly rather than through AR.  AR just issues the command to CATT,
it doesn't performing the casting natively.  So, you would have to try the
commands in your OS and see what errors CATT is posting.  if you have AR
installed on your OS, then CATT is already installed.  You would just have
to run "catt stop -f" and see what happens.  If it is installed in a docker
container, you should be able to run "docker exec catt stop -f" or
something similar, depending on your docker container.

**Comment by greghesp** [comment]
@DevTodd AR is just executing the CLI for [CATT](https://github.com/skorokithakis/catt)

There is some strange behavior with casting whereby it doesn't always pick up all the devices on the network.  I don't think this is an issue linked to CATT either, as I've experienced the same issue when searching for devices from Chrome.

Regarding the stop issue, can you drop an issue on the CATT repo?  I had this issue initially with the Home Hub, I believe this was due to a firmware update on the Hubs.   CATT then put in a workaround which triggered a blank cast and then killed that, not sure if that's still happening.

The commands AR calls is simply `catt -d <device> stop` or `catt -d <device> stop -f` if using force

**Comment by DevTodd** [comment]
The issue was determined to be caused by attempting stop on multiple devices at once.  For some reason the Max wouldn't trigger but the other multiple hubs would.  I changed the commands to stop them 5 seconds apart from each other and the Max stops as expected.

For additional explanation, in case someone else comes across this, I was using motion sensors to trigger nest hubs to display nest cams on motion activation and then disable the stream 30 seconds later if motion was no longer detected.  We have 6 hubs in the house and the one Max didn't like turning off and would therefore continue to stream the cam.  Changing the stop time so that the hubs don't all stop at the same time fixed it.
