### ISSUE TITLE
"blip" audio sound before and after casting an mp3 local file 

### ISSUE THREAD

**Issue by ctcoder5** [greghesp/assistant-relay#193]
When casting a local mp3 file I hear a very recognizable "Blip/exclamation" sound before and after the mp3 audio plays on the assistant speaker. I tried casting to 2 different speakers and can also reproduce in the Assistant Relay sandbox. Running 3.3.2 Relay Assistant.

{
    "device": "Kitchen Speaker",
    "source": "/home/pi/bell-main/doorbell-2.mp3",
    "type": "local"
}
 Casting local file /home/pi/bell-main/doorbell-2.mp3...
0|www  | Playing "doorbell-2" on "Kitchen Speaker speaker"...
0|www  | Serving local file(s).
0|www  | 192.168.x.xx - - [24/Jul/2020 20:36:27] "GET /?loaded_from_catt HTTP/1.1" 206 - audio/mp3 - 103.04 KB
0|www  | POST /cast/ 200 35221.574 ms - 16

Raspberrry Pi os:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**To Reproduce**

**Expected behavior**
The doorbell mp3 file played with no extra sound before and after the mp3 is played.

**Screenshots**

**Desktop (please complete the following information):**
-  Platform [Raspberry Pi v3]
 - Browser [chrome]
 - Version [v3.3.2]

**Additional context**

**Comment by ryancasler** [comment]
What you are asking for isn't possible.  When casting any file to a Google Home device (speaker or display) the "blip" you are describing is added by Google.  This happens when you "cast" any media to your speaker or display with any program.  I routinely watch TV shows and movies on my Lenovo display in the kitchen.  When I first connect to my display with my phone through Plex, I get the exact same "blip" as you do when you play an MP3 file through Assistant Relay.  There is no way to get rid of that sound when your primary purpose is to cast an audio file.

You can mute the display if you are casting something that is visual only, like a camera feed or home automation dashboard, by first muting the speaker.  Then you won't get the sound but you would also not get the sound you are requesting the speaker to play, so it would defeat the purpose in your case.

Sorry to disappoint but this isn't something that can be adjusted from Assistant Relay as it is a function that is inherrent to the Cast functionality of the speaker.

The only other alternative you have is to use a full-fledged Chromecast device, either the current Chromecast or the now discontinued Chromecast Audio.  Those devices will not play the "blip" noise when casting media to them.  But a Chromecast only has an HDMI output so you would have to have it connected to a TV and the TV would have to be on and tuned to the Chromecast when the audio was played.  So, not a practical solution for the long-term.  

Sorry I didn't have a happier answer for you.

**Comment by ctcoder5** [comment]
Ok, Sounds like I don't have much options, but good to know.  Just curious, why does Google add the "blip". Is there any purpose behind it?

**Comment by ryancasler** [comment]
If you could just play sound through your speaker with absolutely no warning, that could be quite startling.  I can imagine kids all of the world scaring the crap out of their parents by cranking up the volume to 10 and playing something like a barking dog.  I know I would jump out of my skin.  At first the "blip" bothered me too.  But eventually I didn't even notice it when I have another noise after it.  But I also use the it as a very gentle notification, like late at night.  I send a silent MP3 to the speaker so all I get is the little blip.  That lets me know certain things have happened that need my attention.

**Comment by ctcoder5** [comment]
yea, that makes sense, I will just play a longer mp3 and will get used to it. Thanks for your quick responses.

**Comment by greghesp** [comment]
@ctcoder5  The before blip you're hearing is part of the casting protocol.  The reason you hear it after though is something to do with how CATT kills a session.  There was a bug with the Home Hubs I reported where when a playback in a session ending, it wouldnt close the session.

They ended up forcing it to close by starting a new session and immediately killing it.  I wonder if that's what you're seeing
