### ISSUE TITLE
commands are identical to voice but don't work with API

### ISSUE THREAD

**Issue by glentakahashi** [greghesp/assistant-relay#56]
I'm seeing an issue where if I issue a custom command like "play spotify" the api responds with "Sorry I don't know how to help with that" but if I talk to my google home and say that it works perfectly.

Even when going to myactivity.google.com I'm seeing that the service is picking them both up identically but providing different responses. I assume I messed something up with my credentials, but I'm able to use broadcast messages fine, ask some basic questions, but things like paying media don't work. Do i need to change app configs to expose additional permissions?

**Comment by john159753** [comment]
I am seeing this as well. To add, I can successfully ask the assistant-relay to "stream my {nest cam} to my {cast device}"; that's about the only item I can cast.

At this point i'm unsure in which of three points the problem lies.
1.  The Assistant Relay
2.  The google-assistant NodeJS module
3.  The actual Google Embedded Assistant "google.assistant.embedded.v1alpha2"

**Comment by kmlucy** [comment]
I'm having the same issue. Some commands work fine and others don't. For example, "turn off the office lights" works, but, "turn off the bedroom tv" doesn't. I just get back, "Sorry, something went wrong. When you're ready, give it another try." The same command works fine via voice.

**Comment by VPeeters** [comment]
This issue may have something to do with this: https://github.com/endoplasmic/google-assistant/issues/52#issuecomment-402062620.

**Comment by jacoblo** [comment]
Same problem here. In My Activity stream its evident that these commands work when initiated on my Home or Mini, while when the source is "Google Assistant SDK" it does not work. Same with commands such as "Play X on YouTube on Chromecast" that otherwise would work.

Leaves the question, any way around this?

![img_5297](https://user-images.githubusercontent.com/18484639/47180477-f81f1180-d320-11e8-8ee6-df1d435a3afd.PNG)

**Comment by nickyromeijn** [comment]
Are there any updates on this? I'm having the same issue, commands regarding to Spotify don't work with the api but do work when voiced.

I wanted to wrap this lib into a home assistant plugin but if this feature is not working it's rather pointless.

**Comment by ryancasler** [comment]
Assistant relay mimics a home device, that's how it is able to issue broadcasts and general commands.  But anything about playing music or casting media is also controlled by the device's setup in the Google home app.  For a Google home mini speaker, you have to select which device is the default TV for video.  And it is the default device for music unless you choose a different one.  Since you can't do that with assistant relay, because it isn't really a device, I suspect these command will never work correctly.  In the case of the music, it very well may be trying to play it on the Assistant Relay device.  The node.js assistant SDK has support for native speaker and microphone.

**Comment by kmlucy** [comment]
If that were the case, you should be able to get around it by providing a command like 'play xyz on the bedroom speaker'. You can always override the default if you want to play somewhere else.

**Comment by ryancasler** [comment]
You can try...but I don't think that's going to work.  Because it's not a GH device.  It's just pretending to be.

**Comment by kmlucy** [comment]
I tried a workaround to for the command 'turn off the xyz tv', which doesn't work for me. I created a routine in the Home app to execute that command, which works fine. The problem is that when I pass the routine command phrase into Assistant Relay, it doesn't seem to recognize the routine phrase. Has anyone figured out how to get Assistant Relay to work with routines?

**Comment by atwc** [comment]
I am also verry interested in this issue with spotify. 
Is there any progress?
Routine could be a good workaround.

**Comment by greghesp** [comment]
No workaround unfortunately,  Google don't currently support it.  As soon as they do, the command will just work

**Comment by kmlucy** [comment]
Just FYI, I am now able to use commands like 'turn off the bedroom tv' successfully when I wasn't before. Maybe the commands other people were having issues with will work now too.

**Comment by rccoleman** [comment]
I just closed the issue I created for a similar reason.  Weirdly, sometimes things like "Watch CNN" work and sometimes they don't.  It doesn't seem to be impossible, but I haven't been able to figure out what's causing the different responses.

**Comment by codahq** [comment]
@greghesp Just out of curiosity, why can't it show up in the Google Home app?  The Google Voice Kit which is just the SDK running on a RPI ZW shows up and you can do things to it in the home app.

**Comment by greghesp** [comment]
@codahq do you have a link with more info?

**Comment by codahq** [comment]
https://aiyprojects.withgoogle.com/voice

It comes with a RPI ZW, some cardboard, button and wires.  You flash a SD Card, setup the SDK, and register a project in the developer console.  It's been a really long time since I set this up so the project I used is gone but I still have it as a speaker in the Home app.  When I asked it to play music it worked as well if I remember correctly.

**Comment by codahq** [comment]
Yeah, I could play music.  I just setup another project following the instructions I linked there.  There is a demo in the distro located at ~/AIY-projects-python/src/examples/voice/assistant_library_with_button_demo.py.  This demo lets you say things like...  "Play music on office speaker" and it works.

![image](https://user-images.githubusercontent.com/6679555/72574241-9b910600-3885-11ea-940e-d90b20bd99c0.png)

**Comment by codahq** [comment]
https://youtu.be/-20CPFm0PHc

Let me know once you watch it.  I'm going to unlist or delete.  I don't want it sitting out there too long.

**Comment by greghesp** [comment]
Hmmm that's interesting. I'll have a look.
I have a feeling it's because that uses some native python, whereas to integrate with GA elsewhere, you have to use GRPC bindings

**Comment by greghesp** [comment]
Although this is what confuses me. It literally says on the AIY website:

I want to use my Voice Kit with other Google devices (Home, Chromecast, etc)

At this time the AIY Voice Kit is not compatible with other Google devices.

**Comment by codahq** [comment]
Well, maybe it won't pan out but it seemed like it might be worth looking into.  Thanks in advance if you do some digging.

**Comment by ryancasler** [comment]
I'm thinking this has something to do with the fact that you have to use the software that supports the AIY Voice kit, which means it will not accept text commands from other devices but only works when the command is spoken to the voicekit.  That's the difference here.  The Assistant SDK allows you send the command to Assistant without someone actually having to speak into a device.  You have to speak into a device with the voice kit.  

The reason this makes a difference is that it's a lot easier to spam the servers with thousands of text requests that can be computer generated.   That's a lot harder to do with a thousand different voice requests.    That's the best guess I can come up with.  Because when you issue the command to GAR, it's not like the assistant doesn't understand what the request is.  It does.  It responds with "I don't know how to help with that yet." as in the command isn't supported.

**Comment by codahq** [comment]
Uh... no.  I don't think that's it at all. This is running on Google's Python Assistant SDK and includes some other tidbits and examples for the AIY projects from the SD card image that anybody can get [here](https://github.com/google/aiyprojects-raspbian/releases) and install on any RPI.  It's just Raspbian.  It can support text commands from other devices if we built essentially this same project in python.  A project like that may already exist even.  It could spam Google's services just as easily.  It doesn't need voice.  The only thing that makes the AIY Kit itself unique is that it has a voice hat for voice processing as far as I can tell.  Other than that it's just a raspberry PI running the Python Assistant SDK.

It's possible Greg pulls it apart and he just finds that it's because it's the native python GA library like he guessed.  Maybe it has something to do with the voice hat itself.  But it might be as simple as the way the project registers the device instance (and that's why it shows up in the Google Home app) or something else similar.  All I know is I'm not looking into it but I thought I would mention it.  I'll be grateful if grephesp looks into it but I don't have the bandwidth to do it right now.

If these voice kits were still available it would have been a very neat way to run a type of Google Assistant relay (probably written in Python) because it would essentially support almost everything using the libraries on the AIY projects Raspbian image.

**Comment by codahq** [comment]
> Although this is what confuses me. It literally says on the AIY website:
> 
> I want to use my Voice Kit with other Google devices (Home, Chromecast, etc)
> 
> At this time the AIY Voice Kit is not compatible with other Google devices.

That probably means that it can't be cast to or put in speaker groups which I can do neither?

**Comment by greghesp** [comment]
I had a slight dig into this and I think @codahq is right.

The AIY is using the deprecated Google Assistant Python SDK which, annoyingly looks like it let you perform some extra commands that the new Assistant SDK can do.

I don't particularly want to hack in an deprecated version of an SDK either to be honest. We all know what Google are like when it comes to pulling the plug, so it'll likely just stop working at some point

**Comment by ryancasler** [comment]
> I'm thinking this has something to do with the fact that you have to use the software that supports the AIY Voice kit,

I'm not seeing where that isn't exactly what I said.  But whatever.

**Comment by codahq** [comment]
@greghesp , I had a slight dig into this as well and it appears that the secret sauce may indeed be device instance registration (regardless of library)  

Does the library we use support anything like the python library for device instance or model registration?  This part, I imagine, isn't going away regardless of the library used.  A device needs to be registered either way I would assume.

https://developers.google.com/assistant/sdk/reference/device-registration/device-tool

This assumption is backed up by a thread I found [here](https://community.openhab.org/t/orangeassist-google-assistant-integration/63675) about another project which sets up a relay to the Google Assistant.  I realize this project uses the same python Google Assistant SDK as the voice kits but there is specific wording here to seem to show that as soon as the device is registered it will show up in the Google Home app.

I don't know a lot about which part Google is deprecating but it doesn't appear this part is deprecating?  If you follow the "Google Assistant SDK" link in the breadcrumb of that device tool link it goes here.

https://developers.google.com/assistant/sdk

No mention of deprecation.  It talks about the gRPC API and all of the languages supported and doesn't mention deprecation at all there either.

If you go to the "[Actions Console](https://console.actions.google.com/)" and choose your project you can still find a hidden link to register your model through the webpage if you didn't create one when the project was created.  Click "Develop".  You should be at a URL that looks like this:

https://console.actions.google.com/u/0/project/[your_project_id]/firebase

If you remove "firebase" and add "deviceregistration/" then you are at the model registration step I presume.  URL would then be:

https://console.actions.google.com/u/0/project/[your_project_id]/deviceregistration/

(Once you register a model "Device registration" always appears in the left nav of the "Develop" tab.)

This steps creates an OAuth JSON file that I presume must be used with the gRPC API to register the device model or instance?  It talks about this JSON file and how to use it in the python library in the first link of this post.  Does the node library have a device registration tool? 

https://github.com/googlesamples/assistant-sdk-nodejs

It seems to be showing that you use Python library to register a device even for use with the node library.  Inconvenient for sure for everybody to have to install python to register the device but have you ever tried that?

**Comment by greghesp** [comment]
I've actually tried that already as below and have the device showing in my Google Home app, although I can't remove it now.

![image](https://user-images.githubusercontent.com/768908/73253273-1cb89900-41b4-11ea-8400-c22fd46b342c.png)

I imagine this is the way to do it, but I cannot for the life of me figure out the correct way of doing it.  There must be a process to follow, I just cant figure out what it is

**Comment by codahq** [comment]
Did a little more messing around with this today...  mostly to see if I could remove my devices that are shown in the Google Home app.  The good news: I managed to remove mine eventually.  The bad news: for me it required me to delete my home and recreate it.  

According to the interwebz we should have been able to go to Assistant Settings -> Services and then scroll down to the button to find the device and unlink it. While I was able to do this it did not remove it from my home.  Once I deleted the home and recreated it was gone though.  Bad.

Anyway...  I thought I would mention that if it bugs you as much as it bugs me to have a device there that is not connected to anything.  (I added my voice kit a bunch of times so I had a bunch of devices that I couldn't delete.)

Once your device showed up where you able to configure a location for it and enable personalized results?

**Comment by greghesp** [comment]
@codahq  I'll try again, but I thought that the personalisation was at a service level, not a device level?

I spoke to Google developers about that bug, and they gave me a workaround literally a few hours ago.

You can delete them throughout the API fine, but if you've deleted the project before deleting the devices you've had it.

To remove them then,  Make a test home, move the devices to the test home, delete the test home.

**Comment by codahq** [comment]
Oh, that's great news about the device deleting.  I didn't realize you could move devices between homes.  That's awesome and awful at the same time.  It's awesome that I won't have to delete my home again but awful that I deleted my home already when I didn't need to. :(

Anyway, I guess personalization could be at the service level?  I don't know really.  All I know is that I have those settings available to me at the device level for the voice kit.  

![Screenshot_20200208-212710](https://user-images.githubusercontent.com/6679555/74096346-ec79d000-4aba-11ea-9893-e3b70f0975ff.png)

How did you get to talk to some Google developers by the way?  Are they a group that would be familiar with what you are trying to accomplish here and could shed some light on the situation?

**Comment by greghesp** [comment]
Hmm.

I'll add the device again and see if I can get it working. I've been building CATT into AR as a workaround instead 🤣

As for the developers, it's just a support email for  Actions on Google I'm afraid :(. I guess I could ask them and see what they say.
https://developers.google.com/assistant/support

**Comment by codahq** [comment]
> I guess I could ask them and see what they say.

Worth a shot I guess.  And if you do it might be a good idea to link this repo and the supporting SmartThings (and Hubitat) pages with your inquiry.  You're kind of a big deal now.  If we're lucky they might already know who you are.  There are a fair number of people using this.  

My guess is, if we're dealing with the typical low level support personnel, they'll just immediately say it's not supported or possible though regardless of whether it is or isn't.  There's a lot of red tape to cut through at Google to talk to anybody who actually knows what is going on.  The support level is trained to be simple and difficult.  I've had **horrible** experiences with the app approval group and I've stopped deploying my Android apps to their store because of it.

**Comment by greghesp** [comment]
I've registered another device, and enabled personalised results for it but still no joy.  I tried triggering my routine called Goodnight and all it did was respond with "goodnight"

I'll reach out to support, see what's possible and what's not, and why some stuff can do it and some can't

**Comment by greghesp** [comment]
Reached out to the AoG support team.  They just pointed me to the Stack Overflow tag for SDK support, which has pretty much every question unanswered...

Will keep digging

**Comment by MaciejOlszewski** [comment]
I'm having the same issue and funny enough, this (missing) functionality was my only motivation to install the AR 😂

**Comment by Progaros** [comment]
No Fix just a workaround:
I placed an old bluetooth speaker next to my google home and when I want to execute a command I send a prerecorded audio message to the speaker.

**Comment by bdn76** [comment]
I have the same issue with 3.3.2b. Any news about workaround?

**Comment by greghesp** [comment]
@bdn76 What are the commands you're sending?  Some aren't supported by the assistant sdk

**Comment by bdn76** [comment]
Not work play music from any source, for example, "play some music" or "play Depeche Mode from Google Play Music on Kitchen player"

**Comment by ryancasler** [comment]
Those commands are not supported by the Google Assistant SDK so they will not work from Assistant Relay.  Not all of the commands you can speak to your Google Home speaker are supported by the SDK.  And Google is the only one who can make changes to that.

**Comment by greghesp** [comment]
Closing.  This is an SDK limitation.  Other implementations seem to be using a hacky version of the old Python implementation that has been deprecated.

**Comment by henning334** [comment]
+1 to this issue. I've read through it and as i understand it there's limitations in the SDK, but please keep this functionality in mind for later or keep trying

**Comment by ryancasler** [comment]
There is nothing that anyone outside of Google can do about this.  AR uses an SDK (software development kit) released by Google in order to use the Assistant Service.  They are the ones imposing the limitation so they are the only ones that can lift it.  There is nothing you could ever possibly do inside of AR, even if you had magic abilities, to get it to work.

**Comment by Daniele70** [comment]
First of all, many thanks to Greg and all other contributors : this project is very usefull !
Now my problem … may-be someone can give me some suggestions.
I installed assistant realy to be able to interface openhab to devices not supported in openhab but compatible with Google.
In particular a door lock that I’d like to close thru openhab.
Since my competencies are limited, I really followed all the instructions and now everything is running fine. In the sandbox I can send commands to google assistant and broadcast messages to selected google home mini.
Unfortunately there is something not yet working : when I try to close my door or simply I ask : « Who am I ? » I get as answer that I need to enable personal results access.
I immediatly get on my phone a pop-up request to grant personal results, but the request is from an empty device name. In this case if I try to activate personal results thru the slider, the app crashes.
If I try to fill a name it crashes also or do not register so no progress.
Tryed on several android devices but always same result (so not a problem of the android app)
NB : the SDK do not appear as a device in Google Home (not sure this will make any difference)
I tryed to connect assistant realy with « TV and limited input device » handly created or with credentials coming from the device created in the project but no difference.
I’m struggling to understand if the problem is coming from assistant relay not transferring in some way the device identification or from a problem on google API.
But it seems some peoples could make it work and this shouldn’t be a limitation of the API since.
I’m wondering if I missed something in terms of further device registration after the automatic procedure going thru the registration tool but I’m really at the limits of my skills 😊

Any suggestions is welcome !
Thanks !

PS : I could progress removing everything and registering the device directly from command line thru registerDevice.js. After that the device appear in Google Home, in the Action console under my project and also as credentials in the API ... but always same result. It seems the request arrive with no link to the device created thru registerDevice.js

**Comment by Bjar0203** [comment]
I have same experience as @Daniele70 

1. Trying to use sandbox to add a note to my google keep.
2. I get an answer in the Sandbox environment that I need to enable personal results
3. I also get a Pop-up on my phone in google home app on my phone to "Allow personal answers"
4. When i click "Allow" the device name is not showed and when enabling Personal Results the Google Home app crashes
5. If I instead write a name in "Device Name" I am able to enable Personal results, but next time I am sending command in sandbox the results is the same and it doesn't seem to remember the personal result setting. I am also not sure what I am supposed to write as Device Name.

Hope some brilliant people out there knows how to fix this.

**Comment by Daniele70** [comment]
Thanks for the comment.
When I'll have more time, even if I have a limited understanding of what I'm doing, I'll make some additional tests to try to figure out if this is coming from a change / bug in the google API or from a problem in the local config of assistant relay.
If someone could confirm it's still working for him or not, this could help me to look in the right direction.
Thanks !
