### ISSUE TITLE
repeat after me command not working

### ISSUE THREAD

**Issue by avraham** [greghesp/assistant-relay#59]
Hi,

I'm trying to use the repeat after me command to make google assistant say something but it's not working even with the converse attribute. 
I know I can use the broadcast command, but I was trying this as an alternative way.

I can see the command on my history but I don't get a response. Everything it's working for other commands like tell me a joke.

**Comment by ryancasler** [comment]
I would suspect that this won't work because the device you are issuing the command to is Assistant Relay and it doesn't have a speaker.  Relay works by using the Assistant SDK and mimicking a GH device on your network to issue broadcasts that are picked up by all the devices on your network to play.  When you issue a command like "repeat after me" the device that is going to try and do that is your Assistant Relay.  This is not a failure of Relay, it is the wrong command.  If you want GH to repeat after you, you have to say it to GH.

**Comment by greghesp** [comment]
Ryan is correct.  You're asking the relay to repeat after me, not  your google home devices
